/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ceaserCipher;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) {
    Scanner keyboard = new Scanner(System.in);
    System.out.println("Hello Welcome to Caesar Encryption Program");
    System.out.println("Enter text for encryption:");
    String textInput = keyboard.nextLine();
    System.out.println("Enter desired key");
    int shiftKey = keyboard.nextInt();
    CeaserCipher myResult = new CeaserCipher();
    String result = myResult.encrypt(textInput,shiftKey);
    System.out.println("The encrypted text is: "+result);
    String decryptResult = myResult.decrypt(textInput,shiftKey);
    System.out.println("The decrypted text is: "+decryptResult);
    }
}
